
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Annuaire", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Annuaire {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPersonneList", targetNamespace = "http://service/", className = "service.AddPersonneList")
    @ResponseWrapper(localName = "addPersonneListResponse", targetNamespace = "http://service/", className = "service.AddPersonneListResponse")
    @Action(input = "http://service/Annuaire/addPersonneListRequest", output = "http://service/Annuaire/addPersonneListResponse")
    public void addPersonneList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws NameNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTelephone", targetNamespace = "http://service/", className = "service.SearchTelephone")
    @ResponseWrapper(localName = "searchTelephoneResponse", targetNamespace = "http://service/", className = "service.SearchTelephoneResponse")
    @Action(input = "http://service/Annuaire/searchTelephoneRequest", output = "http://service/Annuaire/searchTelephoneResponse", fault = {
        @FaultAction(className = NameNotFoundException_Exception.class, value = "http://service/Annuaire/searchTelephone/Fault/NameNotFoundException")
    })
    public String searchTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws NameNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPersonne", targetNamespace = "http://service/", className = "service.AddPersonne")
    @ResponseWrapper(localName = "addPersonneResponse", targetNamespace = "http://service/", className = "service.AddPersonneResponse")
    @Action(input = "http://service/Annuaire/addPersonneRequest", output = "http://service/Annuaire/addPersonneResponse")
    public void addPersonne(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNom", targetNamespace = "http://service/", className = "service.GetAllNom")
    @ResponseWrapper(localName = "getAllNomResponse", targetNamespace = "http://service/", className = "service.GetAllNomResponse")
    @Action(input = "http://service/Annuaire/getAllNomRequest", output = "http://service/Annuaire/getAllNomResponse")
    public List<String> getAllNom();

}
