
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnnuaireService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9191/annuaire?wsdl")
public class AnnuaireService
    extends Service
{

    private final static URL ANNUAIRESERVICE_WSDL_LOCATION;
    private final static WebServiceException ANNUAIRESERVICE_EXCEPTION;
    private final static QName ANNUAIRESERVICE_QNAME = new QName("http://service/", "AnnuaireService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/annuaire?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANNUAIRESERVICE_WSDL_LOCATION = url;
        ANNUAIRESERVICE_EXCEPTION = e;
    }

    public AnnuaireService() {
        super(__getWsdlLocation(), ANNUAIRESERVICE_QNAME);
    }

    public AnnuaireService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANNUAIRESERVICE_QNAME, features);
    }

    public AnnuaireService(URL wsdlLocation) {
        super(wsdlLocation, ANNUAIRESERVICE_QNAME);
    }

    public AnnuaireService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANNUAIRESERVICE_QNAME, features);
    }

    public AnnuaireService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnuaireService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Annuaire
     */
    @WebEndpoint(name = "AnnuairePort")
    public Annuaire getAnnuairePort() {
        return super.getPort(new QName("http://service/", "AnnuairePort"), Annuaire.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Annuaire
     */
    @WebEndpoint(name = "AnnuairePort")
    public Annuaire getAnnuairePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AnnuairePort"), Annuaire.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANNUAIRESERVICE_EXCEPTION!= null) {
            throw ANNUAIRESERVICE_EXCEPTION;
        }
        return ANNUAIRESERVICE_WSDL_LOCATION;
    }

}
